#!/usr/bin/Python
# -*- coding: utf-8 -*-
prov_site_map = {
    "beijing": "bj.gsxt.gov.cn",
    "tianjin": "tj.gsxt.gov.cn",
    "hebei": "he.gsxt.gov.cn",
    "neimenggu": "nm.gsxt.gov.cn",
    "liaoning": "ln.gsxt.gov.cn",
    "jilin": "jl.gsxt.gov.cn",
    "heilongjiang": "hl.gsxt.gov.cn",
    "shanghai": "sh.gsxt.gov.cn",
    "jiangsu": "js.gsxt.gov.cn",
    "zhejiang": "zj.gsxt.gov.cn",
    "anhui": "ah.gsxt.gov.cn",
    "fujian": "fj.gsxt.gov.cn",
    "jiangxi": "jx.gsxt.gov.cn",
    "shandong": "sd.gsxt.gov.cn",
    "guangdong": "gd.gsxt.gov.cn",
    "guangxi": "gx.gsxt.gov.cn",
    "hainan": "hi.gsxt.gov.cn",
    "henan": "ha.gsxt.gov.cn",
    "hubei": "hb.gsxt.gov.cn",
    "hunan": "hn.gsxt.gov.cn",
    "chongqing": "cq.gsxt.gov.cn",
    "sichuan": "sc.gsxt.gov.cn",
    "guizhou": "gz.gsxt.gov.cn",
    "yunnan": "yn.gsxt.gov.cn",
    "xizang": "xz.gsxt.gov.cn",
    "gansu": "gs.gsxt.gov.cn",
    "qinghai": "qh.gsxt.gov.cn",
    "ningxia": "nx.gsxt.gov.cn",
    "xinjiang": "xj.gsxt.gov.cn",
    "shanxi": "sn.gsxt.gov.cn",
    "shanxicu": "sx.gsxt.gov.cn",
}
